sudo: required
services:
  - docker
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t ramsrib/k8s-sidecar .
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag ramsrib/k8s-sidecar ramsrib/k8s-sidecar:$TAG
      docker push ramsrib/k8s-sidecar:$TAG
      docker push ramsrib/k8s-sidecar
    fi
